### ISSUE TITLE
Stage I - Volleyball Detection and Tracking

### ISSUE THREAD

**Issue by KosiReq** [shukkkur/VolleyVision#15]
<img width="854" alt="image" src="https://github.com/shukkkur/VolleyVision/assets/54788019/2647323b-dbad-4480-b706-38a76e609324">

OS: Windows 11
Browser: Edge

having issues with the version number here

**Comment by shukkkur** [comment]
1. Go to [model page](https://universe.roboflow.com/shukur-sabzaliev1/volleyball_v2/model/2)
2.Copy 
![347252349-f59048d6-818b-40c4-b820-a288a41d523d](https://github.com/shukkkur/VolleyVision/assets/78250180/607404be-d061-4341-b656-ebd1871799f3)
3. Paste [here](https://github.com/shukkkur/VolleyVision/blob/445e768b7be2dab31d6f909bcc5bcfc2aeda34d9/Stage%20I%20-%20Volleyball/detect.py#L158-L160)
